{LOOP}
    <item>
        <title>{title}</title>
        <description>{content_short}</description>
        <link>{BASE}blog/post/{ID}</link>
        <pubDate>{DTC}{created}{/DTC}</pubDate>
    </item>
{/LOOP}
{ALT}
{/ALT}
